import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { ArrowRight, ArrowUpRight, ChevronDown, ChevronLeft, ChevronRight, Heart, Leaf, MessageCircle, ShieldCheck, Sparkles, UserRound, Video, Brain, Flower2, Check, Menu, X, Play } from "lucide-react";

export const Route = createFileRoute("/")({ component: Index });
const whatsapp="https://wa.me/5524993272763?text=Ol%C3%A1%20Ana%2C%20gostaria%20de%20agendar%20uma%20conversa.";
const services=[
 {t:"Psicanálise",d:"Um espaço de escuta profunda para compreender sua história, emoções e padrões.",img:"https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=900&q=85",i:Brain},
 {t:"Ansiedade",d:"Acolhimento para compreender preocupações, sobrecarga e aquilo que vem tirando sua tranquilidade.",img:"https://images.unsplash.com/photo-1499209974431-9dddcece7f88?auto=format&fit=crop&w=900&q=85",i:Sparkles},
 {t:"Terapia",d:"Um acompanhamento individual para atravessar momentos difíceis com mais clareza e cuidado.",img:"https://images.unsplash.com/photo-1544027993-37dbfe43562a?auto=format&fit=crop&w=900&q=85",i:Heart},
 {t:"Naturopatia",d:"Um olhar integrativo para hábitos, rotina e bem-estar, respeitando a individualidade.",img:"https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=900&q=85",i:Leaf},
 {t:"Adolescentes",d:"Escuta acolhedora para mudanças, inseguranças, relações e desafios da adolescência.",img:"https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=900&q=85",i:UserRound},
 {t:"Adultos",d:"Para quem deseja se compreender melhor e cuidar daquilo que está pedindo atenção.",img:"https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=900&q=85",i:Flower2}
];
const faqs=[
["Como funciona o atendimento online?","As sessões acontecem por videochamada, em ambiente reservado e acolhedor. Você pode ser atendido de onde estiver, com praticidade e privacidade."],
["Você atende adolescentes?","Sim. O acompanhamento contempla adolescentes e adultos, respeitando a fase de vida e as necessidades de cada pessoa."],
["Como funciona a primeira conversa?","É um momento para você contar o que está vivendo, tirar dúvidas e conhecer a proposta de acompanhamento. Não é necessário chegar com tudo organizado."],
["Psicanálise e terapia são iguais?","São abordagens que podem ter características diferentes. A conversa inicial ajuda a compreender sua necessidade e explicar a proposta de atendimento."],
["A naturopatia substitui atendimento médico?","Não. A naturopatia é complementar e não substitui avaliação, diagnóstico ou tratamento médico quando necessários."],
["Como saber se é hora de procurar ajuda?","Se emoções, ansiedade, relacionamentos ou rotina estão pesando, você já pode buscar um espaço de escuta. Não é preciso esperar chegar ao limite."]
];

function Index(){
 const [slide,setSlide]=useState(0),[test,setTest]=useState(0),[faq,setFaq]=useState<number|null>(null),[menu,setMenu]=useState(false);
 const visible=[0,1,2].map(n=>services[(slide+n)%services.length]);
 const testimonials=[
  ["“Um espaço para respirar, organizar o que sinto e olhar para mim com mais gentileza.”","Experiência de acompanhamento"],
  ["“O atendimento online trouxe praticidade sem perder a sensação de acolhimento e presença.”","Experiência de atendimento"],
  ["“Aprender a perceber meus padrões mudou a forma como encaro minhas escolhas e relações.”","Experiência de processo"]
 ];
 return <main className="site">
 <header className="nav"><a href="#inicio" className="brand"><span>ANA</span> FEITOSA<small>PSICANALISTA · TERAPEUTA · NATUROPATA</small></a><nav className={menu?"nav-links open":"nav-links"}>{[["Sobre","#sobre"],["Atendimentos","#atendimentos"],["Como funciona","#processo"],["Dúvidas","#faq"]].map(([x,h])=><a href={h} key={x} onClick={()=>setMenu(false)}>{x}</a>)}<a href={whatsapp} target="_blank" rel="noreferrer" className="nav-cta">Agendar atendimento <ArrowUpRight size={15}/></a></nav><button className="menu-btn" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>

 <section id="inicio" className="hero"><div className="hero-copy"><div className="eyebrow"><span/> CUIDADO EMOCIONAL · ATENDIMENTO ONLINE</div><h1>Um lugar para você <i>se ouvir</i> com mais calma.</h1><p>Psicanálise, terapia e naturopatia com uma abordagem acolhedora para adultos e adolescentes que desejam cuidar da mente, das emoções e da própria história.</p><div className="hero-actions"><a className="btn" href={whatsapp} target="_blank" rel="noreferrer">Agendar minha conversa <ArrowRight size={17}/></a><a href="#sobre" className="quiet-link">Conhecer Ana <ChevronRight size={16}/></a></div><div className="hero-trust"><span><ShieldCheck/> Escuta acolhedora</span><span><Video/> Online</span><span><Heart/> Individual</span></div></div><div className="hero-photo"><img src="https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=1200&q=90" alt="Ambiente profissional e acolhedor"/><div className="photo-label"><b>Ana Feitosa</b><span>Psicanalista · Terapeuta · Naturopata</span></div><div className="round-stamp"><span>ESCUTA</span><strong>·</strong><span>CUIDADO</span><strong>·</strong><span>PRESENÇA</span></div></div></section>

 <div className="green-marquee"><div className="marquee-track">{Array.from({length:2}).flatMap(()=>["ATENDIMENTO ONLINE","ADULTOS E ADOLESCENTES","ESCUTA ACOLHEDORA","CUIDADO INDIVIDUALIZADO","PSICANÁLISE · TERAPIA · NATUROPATIA"]).map((x,i)=><span key={i}>{x}<b>✦</b></span>)}</div></div>

 <section className="intro"><div className="intro-image"><img src="https://images.unsplash.com/photo-1544027993-37dbfe43562a?auto=format&fit=crop&w=1000&q=90" alt="Pessoa em momento de reflexão"/><div className="image-note"><Sparkles/> <span>Seu processo<br/><b>começa com uma conversa.</b></span></div></div><div className="intro-copy"><div className="kicker">Talvez você tenha chegado até aqui porque...</div><h2>Tem coisas que você <i>não quer mais carregar sozinho.</i></h2><p>Ansiedade, pensamentos acelerados, cansaço emocional, inseguranças ou situações que parecem se repetir podem ocupar muito espaço na vida.</p><p>Ter um lugar para falar, ser ouvido e compreender o que acontece dentro de você pode abrir novas possibilidades.</p><a className="btn soft" href={whatsapp} target="_blank" rel="noreferrer">Quero conversar com a Ana <ArrowRight size={17}/></a></div></section>

 <section id="sobre" className="about"><div className="about-copy"><div className="kicker">Quem é Ana Feitosa</div><h2>Cuidar da mente também é aprender a <i>se tratar com gentileza.</i></h2><p>Meu trabalho parte da escuta e do respeito pela história de cada pessoa. Não existe um roteiro pronto para aquilo que você vive.</p><p>Como <b>psicanalista, terapeuta e naturopata</b>, ofereço um espaço de acolhimento para adultos e adolescentes, com atendimento online e olhar individualizado.</p><div className="about-list"><span><Check/> Escuta sem julgamentos</span><span><Check/> Atendimento individual</span><span><Check/> Adultos e adolescentes</span><span><Check/> Formato online</span></div><a className="btn" href={whatsapp} target="_blank" rel="noreferrer">Agendar atendimento <ArrowUpRight size={16}/></a></div><div className="about-collage"><img className="main-img" src="https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1000&q=90" alt="Conversa e acolhimento"/><img className="small-img" src="https://images.unsplash.com/photo-1516307365426-bea591f05011?auto=format&fit=crop&w=500&q=90" alt="Natureza e tranquilidade"/><div className="years">ANA<br/><small>ESCUTA · PRESENÇA</small></div></div></section>

 <section id="atendimentos" className="services"><div className="section-top"><div><div className="kicker">Áreas de cuidado</div><h2>Encontre espaço para aquilo que <i>você está vivendo.</i></h2></div><div className="arrows"><button onClick={()=>setSlide((slide-1+services.length)%services.length)}><ChevronLeft/></button><button onClick={()=>setSlide((slide+1)%services.length)}><ChevronRight/></button></div></div><div className="service-carousel">{visible.map((s,i)=>{const I=s.i;return <article className="service" key={s.t}><div className="service-img"><img src={s.img} alt=""/><span><I/></span></div><div className="service-body"><small>0{(slide+i)%services.length+1}</small><h3>{s.t}</h3><p>{s.d}</p><a href={whatsapp} target="_blank" rel="noreferrer">Agendar conversa <ArrowRight size={15}/></a></div></article>})}</div><div className="dots">{services.map((_,i)=><button className={i===slide?"active":""} onClick={()=>setSlide(i)} key={i}/>)}</div><a className="section-btn" href={whatsapp} target="_blank" rel="noreferrer">Quero saber qual atendimento combina comigo <ArrowRight size={16}/></a></section>

 <section id="processo" className="process"><div className="process-left"><div className="kicker">Como funciona</div><h2>Começar pode ser mais simples do que <i>parece.</i></h2><p>Você não precisa saber exatamente o que dizer. O primeiro passo é simplesmente abrir espaço para conversar.</p><a className="btn light" href={whatsapp} target="_blank" rel="noreferrer">Agendar primeira conversa <ArrowRight size={17}/></a></div><div className="steps">{[["01","Você entra em contato","Chame pelo WhatsApp e conte, do seu jeito, o que está buscando."],["02","Conhecemos seu momento","Conversamos sobre sua história, suas necessidades e suas dúvidas."],["03","Combinamos o acompanhamento","Definimos juntos a melhor forma de conduzir o processo."],["04","Você começa seu processo","Com constância, escuta e espaço para perceber novos caminhos."]].map(([n,t,d])=><div className="step" key={n}><b>{n}</b><div><h3>{t}</h3><p>{d}</p></div></div>)}</div></section>

 <section className="moments"><div className="moments-copy"><div className="kicker">Para diferentes momentos</div><h2>O que está pedindo <i>atenção em você?</i></h2><p>Você pode procurar acompanhamento quando sente que algo precisa ser compreendido, cuidado ou simplesmente colocado em palavras.</p><a className="btn soft" href={whatsapp} target="_blank" rel="noreferrer">Falar sobre meu momento <ArrowRight size={17}/></a></div><div className="moment-orbit">{["Ansiedade","Autoconhecimento","Emoções","Relacionamentos","Mudanças","Adolescência"].map((x,i)=><div className={"bubble b"+i} key={x}>{x}</div>)}</div></section>

 <section className="testimonials"><div className="kicker">Experiências de cuidado</div><h2>Um atendimento que começa pela <i>escuta.</i></h2><div className="testimonial-row"><button onClick={()=>setTest((test-1+3)%3)}><ChevronLeft/></button><div className="testimonial"><div className="stars">★★★★★</div><blockquote>{testimonials[test][0]}</blockquote><b>{testimonials[test][1]}</b><small>Relato ilustrativo • substitua por depoimento autorizado</small></div><button onClick={()=>setTest((test+1)%3)}><ChevronRight/></button></div><div className="dots">{testimonials.map((_,i)=><button className={i===test?"active":""} onClick={()=>setTest(i)} key={i}/>)}</div><a className="btn soft" href={whatsapp} target="_blank" rel="noreferrer">Agendar meu atendimento <ArrowRight size={17}/></a></section>

 <section className="online"><div className="online-photo"><img src="https://images.unsplash.com/photo-1581579186983-ec4a4a1a3d55?auto=format&fit=crop&w=1000&q=90" alt="Atendimento online"/><div className="play"><Play fill="currentColor"/></div></div><div><div className="kicker">Atendimento online</div><h2>Seu cuidado pode acontecer de onde <i>você estiver.</i></h2><p>Tenha um espaço reservado na sua rotina para olhar para si, sem precisar se deslocar. Escolha um lugar tranquilo e esteja presente para o seu processo.</p><div className="online-points"><span><Check/> Mais praticidade</span><span><Check/> Horário combinado</span><span><Check/> Ambiente reservado</span></div><a className="btn" href={whatsapp} target="_blank" rel="noreferrer">Ver disponibilidade <ArrowRight size={17}/></a></div></section>

 <section id="faq" className="faq"><div><div className="kicker">Dúvidas frequentes</div><h2>Antes de começar, <i>tire suas dúvidas.</i></h2><p>Se a sua pergunta não estiver aqui, fale diretamente pelo WhatsApp.</p><a className="btn soft" href={whatsapp} target="_blank" rel="noreferrer">Tirar uma dúvida <MessageCircle size={16}/></a></div><div className="faq-list">{faqs.map(([q,a],i)=><div className={"faq-item "+(faq===i?"open":"")} key={q}><button onClick={()=>setFaq(faq===i?null:i)}><span>{q}</span><ChevronDown/></button><div className="answer"><p>{a}</p></div></div>)}</div></section>

 <section className="cta"><div className="cta-shape">✦</div><div className="kicker">Seu próximo passo</div><h2>Você pode começar com uma <i>conversa.</i></h2><p>Não precisa ter tudo resolvido. Basta dar espaço para o que você está sentindo.</p><a className="btn cream" href={whatsapp} target="_blank" rel="noreferrer"><MessageCircle size={17}/> Agendar atendimento pelo WhatsApp</a></section>
 <footer><div><a className="brand footer-brand" href="#inicio"><span>ANA</span> FEITOSA<small>PSICANALISTA · TERAPEUTA · NATUROPATA</small></a><p>Escuta, cuidado e presença.</p></div><div className="footer-nav"><a href="#sobre">Sobre Ana</a><a href="#atendimentos">Atendimentos</a><a href="#processo">Como funciona</a><a href="#faq">Dúvidas</a></div><div className="footer-phone"><small>Agendamentos</small><a href={whatsapp} target="_blank" rel="noreferrer">+55 24 99327-2763</a><a className="footer-book" href={whatsapp} target="_blank" rel="noreferrer">Agendar agora <ArrowUpRight size={14}/></a></div><div className="footer-bottom">© {new Date().getFullYear()} Ana Feitosa · Atendimento online</div></footer>
 <a className="wa" href={whatsapp} target="_blank" rel="noreferrer"><MessageCircle/><span>Agendar pelo WhatsApp</span></a>
 </main>
}
